apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
data:
  jwt-secret: eUpTRFZweEtVUTFMU2ZybnJzTE42cjZ0bUZkMWk5NUkzekdYanBJcnlPOHpvV2c3ZkRtWUVueXlDbXRLRmgyTUZkNGM3ckZqTjl3S3Npd1JYWUtaOUJLSjVZSFRCeVFpOFE0
  jwt-expiration: MzYwMA==
