apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
type: Opaque
data:
  mongodb-passwords: ""
  mongodb-root-password: cGFzc3dvcmQxMjMK
  mongodb-metrics-password: cGFzc3dvcmQxMjMK
  mongodb-replica-set-key: cmVwbGljYXNldGtleTEyMwo=

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
type: Opaque
data:
  rabbitmq-password: cGFzc3dvcmQxMjMK
