apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: davidandw190/ordering-app_auth:v1
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: '3001'
            - name: RABBIT_MQ_BILLING_QUEUE
              value: billing
            - name: RABBIT_MQ_AUTH_QUEUE
              value: auth
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: jwt-secret
            - name: JWT_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: jwt-expiration
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: orders-secrets
                  key: mongodb-uri
            - name: RABBIT_MQ_URI
              valueFrom:
                secretKeyRef:
                  name: orders-secrets
                  key: rabbitmq-uri
