apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
        - name: billing
          image: davidandw190/ordering-app_billing
          env:
            - name: RABBIT_MQ_BILLING_QUEUE
              value: billing
            - name: RABBIT_MQ_AUTH_QUEUE
              value: auth
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-orders-secrets
                  key: mongodb-uri
            - name: RABBIT_MQ_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-orders-secrets
                  key: rabbitmq-uri
